### ISSUE TITLE
Algorithm changes to support more diverse set of responses

### ISSUE THREAD

**Issue by ericbuckley** [CDCgov/RecordLinker#18]
## Summary
Research into the current algorithm and how we can adjust it to return a response that is non-binary (match vs non-match).  Customers have asked for changes so they can specify a fuzzy area in the matching logic, in which it might be a match and needs to be manually reviewed.

## Acceptance Criteria
- [x] A document that describes how we propose to change the algorithm to meet the above requirements.

## Details / Tasks
There are quite a few places in the current algorithm that we could adjust to return the concept of "might be a match" to the user.  For instance:
 - If only some passes results in a match, and not all
 - If the cluster ratio is in a range
 - If the matching rule is in a range
 - If only some of the evaluators return a positive result, but not all
 - By specifying some of our thresholds as ranges

Because there are so many places in the algorithm that can be adjusted to indicated that we're not positive its a match, but it might be.  We need to make a recommendation based on where the best place(s) are to do so, and make it clear through the definition of the algorithm configuration as to where that adjustment should be made.  Alternatively, it might be possible to just return some sort of confidence interval to the call on how likely we think this is a match, and the customer can make the decision whether a manual review should take place.  Lots of options, but we should do some research and determine where the best place to make the algorithm changes are.

## Background / Context
- [Current record linkage algorithm / glossary](https://docs.google.com/document/d/1YR68Gn6WwLZ_IumsZth_tWO7B1ddGBPmcrtqnFGDzoY/edit#heading=h.w91qlqf974ic)
- [Product requirements for record linkage](https://docs.google.com/document/d/1XS5BOrV45AruNSmXbO2OqsQvK5dTLsmG1ydCkr7hTKs/edit#heading=h.s0i4xvtg1x5p)
- [Record linkage analysis](https://docs.google.com/document/d/1Gwu8V6d2V0IlcK9KQf5kIHPcgoQudln3Y330cqfwJOc/edit#heading=h.5i32wk9voy4)

**Comment by alhayward** [comment]
# Short-Term

## Approach #1
**Apply a configurable range to the [Belongingness Threshold](https://docs.google.com/document/d/1YR68Gn6WwLZ_IumsZth_tWO7B1ddGBPmcrtqnFGDzoY/edit#heading=h.w91qlqf974ic) (a.k.a. [`cluster_ratio`](https://github.com/CDCgov/RecordLinker/blob/55352fdf898a139396a83c016987fcb1fc8122df/src/recordlinker/linkage/algorithms.py#L69))**

&nbsp;&nbsp;&nbsp;&nbsp;Given Belongingness Threshold = [X, Y],

&nbsp;&nbsp;&nbsp;&nbsp;If an incoming Patient record matches...
* < X of existing Patient records in a Person cluster, return _no match_
* \> Y of existing Patient records in a Person cluster, return _match_
* \> X and < Y of existing Patient records in a Person cluster, return _possible match_ (manual review)

## Why?
* While there are many places in the code we could adjust to achieve this feature, this is a good place to start. This is because this feature seems about changing the format of the _output prediction_ (3 classes vs. 2), not the _underlying algorithm_. Therefore, we should avoid changing the underlying algorithm as much as possible. Additionally, the DIBBs team completed extensive [research & literature review](https://docs.google.com/document/d/1XS5BOrV45AruNSmXbO2OqsQvK5dTLsmG1ydCkr7hTKs/edit#heading=h.i6jm8kpl7vkq) to determine how to design the algorithm (i.e., how blocking/matching is performed) that should be retained, unless additional research shows that an alternative algorithm is more performant.
* At a high-level, the output of the RL algorithm is a probability (of whether an incoming Patient record is a match to an existing Person cluster). Currently, the probability is binned into 2 classes: match (> X threshold) or non-match (< X threshold). To implement this feature, we can change the binning to 3 classes: match (> Y threshold), possible match (< Y threshold but > X threshold), non-match (< X threshold). All the underlying algorithm remains the same.

## Approach #2
**Apply a configurable range to the log odds scores (a.k.a. [`true_match_threshold`](https://github.com/CDCgov/RecordLinker/blob/55352fdf898a139396a83c016987fcb1fc8122df/src/recordlinker/linkage/algorithms.py#L73))**

&nbsp;&nbsp;&nbsp;&nbsp;Given a True Match Threshold = [X, Y],

&nbsp;&nbsp;&nbsp;&nbsp;When comparing incoming Patient record _i_ to existing Patient record _j_, if the sum of the log odds scores is...
* < X, return _no match_
* \> Y, return _match_
* \> X and < Y, return _possible match_ (manual review)

## Why?
* This approach would allow for more granular review of possible matches (upon match decision between a record pair, not upon cluster membership).
* This is the approach [NBS](https://cdc.sharepoint.com/teams/CSELS-DHIS-ISB-NBS/_layouts/15/stream.aspx?id=%2Fteams%2FCSELS%2DDHIS%2DISB%2DNBS%2FShared%20Documents%2FNBS%20Modernization%20Project%2FDeDuplication%2FUX%2FPatient%20merge%20configuration%2Emov&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2Eb1b822b6%2Db97a%2D4550%2Db841%2Df79062d17baa) hopes to take.

## Open Questions
1. What motivated the approach to implement possible matches on a **pass level** (upon pass evaluation), rather than on a **Person level** (upon evaluating cluster membership)?
2. In this approach, how may we calculate the Belongingness Ratio to determine whether an incoming Patient record matches a Person cluster? (Would this always be blocked by manual review?)

&nbsp;&nbsp;&nbsp;&nbsp;**Example 1: (Simple)**
* Person A has 10 Patient records.
* Incoming Patient record _i_ blocks on Person A.
* When calculating Belongingness Ratio, Patient record _i_ matches on 6, possible matches on 3, and does not match on 1 out of the 10 Patient records.

&nbsp;&nbsp;&nbsp;&nbsp;**Does the user need to complete 3 manual reviews before Patient record _i_ is determined a match or not?** (Will Patient record _i_ be blocked for comparison against future incoming Patient records in the queue?)

&nbsp;&nbsp;&nbsp;&nbsp;**Example 2: (Scaled)**
* Person A has 100 Patient records.
* Person B has 100 Patient records.
* Incoming Patient record _i_ blocks on Person A and Person B.
* When calculating Belongingness Ratio for Person A, Patient record _i_ matches on 60, possible matches on 30, and does not match on 10 out of the 100 Patient records.
* When calculating Belongingness Ratio for Person B, Patient record _i_ matches on 75, possible matches on 20, and does not match on 5 out of the 100 Patient records.

&nbsp;&nbsp;&nbsp;&nbsp;**Does the user need to complete 50 manual reviews before Patient record _i_ is determined a match or not?**

## Tradeoffs
* By implementing possible matches (and thus manual review) on a pass level, this may create additional manual work. This manual work also blocks the RL algorithm from determining a match decision, which can create bottlenecks for required manual reviews as the MPI grows. In other words, to arrive at a match decision, the user needs to reconcile many possible matches between different permutations of record pairs. Further work is needed to determine how this additional manual work compares against the current manual work to unmerge incorrect matches, vs. the current manual to merge patients in a STLT with no RL system.
* Alternatively, Approach #1 would implement possible matches at a Person level. That is, to arrive at a match decision, the user needs to decide whether the incoming Patient record matches enough of the Patient records in the Person cluster, subjectively (it falls within the "possible match" range). We can build functionality to allow the user to "double-click" into the Patient records of the Person cluster in question, but is not a requirement that they manually review all records (they are just manually reviewing the overall cluster membership decision). We can even display the log odds scores between the incoming Patient record in question and the existing Patient records assigned to the Person cluster, and the user can decide to, say, manually review only those permutations of record pairs with lower log odds scores, based on their discretion.
* While Approach #2 may create additional manual work, it allows for more granular manual review. Approach #1 requires users to manually review _cluster membership decisions_ that are flagged, and optionally review the log odds scores between the incoming Patient record and any of the existing Patient records of the Person cluster in question. Approach #2 requires users to manually review _individual match decisions_ that are flagged, between any incoming Patient record and existing Patient record.

# Long-Term
* Define a reference Patient dataset, on which to test each of the methods described in the above issue. Choose the method with the highest match accuracy.
    * Ideally, this would be production data (identifying & representative). If we are unable to obtain access to production data, we can resort to using [Synthea](https://github.com/synthetichealth/synthea) and leverage parameters in aim to create a diverse set of synthetic Patient records.

## Why?
* Research findings with data will allow us to evaluate which of the above approaches yields the highest match accuracy (i.e., low False Positives or incorrect matches, and low False Negatives or incorrect non-matches). We can leverage the [labeling system](https://docs.google.com/document/d/1Gwu8V6d2V0IlcK9KQf5kIHPcgoQudln3Y330cqfwJOc/edit#heading=h.4ul3i4rk4720) (VA Labels, UK NHS Labels, NCI SEER Labels) the DIBBs team used to evaluate performance metrics.

## Tradeoffs
* If using synthetic data, this approach would entail strong assumptions & limitations. By using synthetic data to evaluate the accuracy of the RL algorithm, we assume the distributions of the synthetic data reflect those of production data, which is [not plausible](https://docs.google.com/document/d/1Gwu8V6d2V0IlcK9KQf5kIHPcgoQudln3Y330cqfwJOc/edit#heading=h.1h9hiyq5rv3t), given the diversity of real-life patient data (within and across STLTs).

# Caveats
The approaches above implement this feature for the DIBBs Enhanced (probabilistic) algorithm. Implementing this feature for the DIBBs Basic algorithm would require a different approach. We should gather more information from NBS to determine whether they are interested in implementing this feature for the Basic algorithm.

**Comment by ericbuckley** [comment]
@alhayward Thanks for all your work here, this is excellent.  I think I'm missing a step around Approach #2.  The `true_match_threshold` is used to determine if the incoming Patient is a match to an existing Patient.  If that existing Patient is only 1 of 10 Patients in the cluster, how do we make the decision of whether the incoming Patient belongs?  Do we average up all the match scores?

**Comment by alhayward** [comment]
@ericbuckley Yes, that's the main open question I had with Approach #2 too. Here are a few paths forward that come to mind:

**1. Require the completion of manual review(s) before a decision is made.**

&nbsp;&nbsp;&nbsp;&nbsp;In this approach, in the example you give above, the RL algorithm would be blocked from making the decision of whether the incoming Patient belongs to this Person cluster, until the user reconciles the 1 possible match. After this manual review is completed, the RL algorithm can continue and make the final match decision. (This is where I think Approach #2 can create additional manual work and bottlenecks of manual reviews as the MPI scales.) 

&nbsp;&nbsp;&nbsp;&nbsp;This also raised the follow-up question of: If the RL algorithm is blocked from making a decision about whether the incoming Patient belongs to this Person cluster, are the other Person clusters found in Blocking (if any) evaluated for cluster membership (does the RL algorithm `continue`)? If so, this opens up the possibility that the incoming Patient matches with _another_ Person cluster, but if 1 had been reconciled beforehand, it would have had a stronger Belongingness Ratio for the first Person cluster and should have been matched with that one. This would result in an incorrect match, and may require unmerge down the line.

**2. Flag the manual review(s), but don't require their completion for a decision to be made. Calculate the Belongingness Ratio as usual.**

&nbsp;&nbsp;&nbsp;&nbsp;The RL algorithm continues as usual and is not blocked by manual reviews, although they are flagged.

&nbsp;&nbsp;&nbsp;&nbsp;In this approach, this feature becomes more of a _flag_ for possible or "low-confidence" matches (i.e., match probabilities that are not significantly close to 0 or 1), rather than a blocker requiring manual review(s).

**3. Exclude the possible matches from the calculation of Belongingness Ratio, and continue RL algorithm as usual.**

&nbsp;&nbsp;&nbsp;&nbsp;This sounds like the approach you describe above.

**Comment by ericbuckley** [comment]
@alhayward how would approach 3 work with the DIBBS_BASIC algorithm, or any algorithm that a customer creates that doesn't use a log odds evaluation function?

**Comment by alhayward** [comment]
@ericbuckley In the Caveats above, I note that these 3 Approaches apply to the DIBBs Enhanced algorithm. We should ask NBS if they are interested in implementing this feature for the Basic algorithm, as that would entail a different approach.

**Comment by ericbuckley** [comment]
Ah sorry, I missed the Caveats section.

The goal is to allow customers to write their own algorithm configurations.  We'll always want to provide a default, something that customers can use out of the box and know it should be reliable.  That said though, we very much want to give customers the flexibility to adjust the algorithm configuration to THEIR needs.

Related to the above approaches, have you been thinking?
1. That this would be a short-term approach in that we ask any customer to ONLY use the log-odds evaluators and feature matchers for the time being, but in the long-term we will alter the algorithm so they can use additional comparison functions.
2. We should remove all non-log-odds functions from the matchers module, and limit users to only those functions going forward?

**Comment by ericbuckley** [comment]
@alhayward what do you think about an adjustment like this to our comparison function?  I'm not sure how this will feed into the person cluster question, but I'm thinking that when we evaluate an incoming patient to an existing one, we'd want to use the number of feature comparisons in our calculation.  As the more comparisons that are used, the more likely that it's a match (assuming the results are positive).

```patch
diff --git a/src/recordlinker/linking/link.py b/src/recordlinker/linking/link.py
index 38d6b24..174ed58 100644
--- a/src/recordlinker/linking/link.py
+++ b/src/recordlinker/linking/link.py
@@ -83,7 +83,7 @@ def add_person_resource(
     return bundle
 
 
-def compare(record: schemas.PIIRecord, patient: models.Patient, linkage_pass: dict) -> bool:
+def compare(record: schemas.PIIRecord, patient: models.Patient, linkage_pass: dict) -> float:
     """
     Compare the incoming record to the linked patient
     """
@@ -101,7 +101,16 @@ def compare(record: schemas.PIIRecord, patient: models.Patient, linkage_pass: di
         # Evaluate the comparison function and append the result to the list
         result: float = func(record, patient, schemas.Feature(field), **kwargs)
         results.append(result)
-    return matching_rule(results, **kwargs)
+
+    # Aggregate the comparison scores into a single matching score (0-1)
+    base_score = matching_rule(results, **kwargs)
+
+    # Adjust the score based on the number of features matched
+    # More features used -> higher score
+    weighted_score = base_score * (len(funcs) / len(models.Feature))
+
+    # Optionally cap the score at 1.0
+    return min(weighted_score, 1.0)
 
 
 def link_record_against_mpi(
```

**Comment by DanPaseltiner** [comment]
I'm still thinking through how approach 3 would work, but we may want to consider a median instead of a mean to compute an aggregate score to guard against the impact of outliers.

**Comment by alhayward** [comment]
@ericbuckley Let's chat Parking Lot 10/8 about your proposals, as well as the outcome of today's meeting with DIBBs:
* **Short-term:** Recommend Approach #1. It is the first approach that came to mind for each of us, and is the simplest & most feasible to implement given the December timeline. We also discussed how it can handle the edge cases you identified that motivated Approach #3: the user can increase the log odds score cutoff (i.e., [`true_match_threshold`](https://github.com/CDCgov/RecordLinker/blob/55352fdf898a139396a83c016987fcb1fc8122df/src/recordlinker/linkage/algorithms.py#L73)) to bias towards being more conservative when returning a "match" result, in order to reduce False Positives. 
    * Explore re-running the RL algorithm in batch overnight, to reconcile cases where 2 Person clusters look very similar, and in reality should be 1 Person (similar to the edge case you identified).
* **Long-term:** Explore Approach #3 further when we have data to test all 3 Approaches & compare their match performance against each other (What do the Person clusters look like in each of these 3 Approaches? / How do they differ? What do the False Positive cases look like in each of these Approaches?)

2 questions re: your proposals:
1. What other evaluators and/or comparisons are you envisioning beyond log odds? Do STLTs want the flexibility to choose what fields are used for blocking/matching, AND the flexibility to change the underlying matching logic? I imagine it will be difficult to support any and all evaluators/comparisons possible... Are you thinking more from the perspective of: Can we develop a standard algorithm definition framework, where the evaluators/comparisons can be user-defined and the corresponding thresholds user-tuned?

FWIW, from my understanding, while the Basic algorithm is available to STLTs as a deterministic option that is more explainable and simpler, most STLTs would opt for the Enhanced algorithm because it is more performant because it is probabilistic (e.g., NBS uses a probabilistic approach). With that, we could choose one of the above Approaches and say:
* Basic algorithm: Available for users - remains the same*
* Enhanced algorithm: Available for users - now enhanced with new feature for returning "possible match" results

*The above would apply if we implement Approach #3, but thinking more about it, Approach #1 can also apply to the Basic algorithm (since Basic also uses Belongingness Threshold, a.k.a. [`cluster_ratio`](https://github.com/CDCgov/RecordLinker/blob/55352fdf898a139396a83c016987fcb1fc8122df/src/recordlinker/linkage/algorithms.py#L37), just with stricter (non-probabilistic) matching criteria).

2. Can you explain more about this weight `(len(funcs) / len(models.Feature))` and why it is predictive of a match? Just because the user configures the algorithm to use more matching fields, doesn't necessarily mean the RL algorithm is more accurate (adding more data fields can actually make the prediction less accurate, as it can incorporate noisy data rather than relying on a few blocking/matching fields [shown to be predictive of a match](https://docs.google.com/document/d/1XS5BOrV45AruNSmXbO2OqsQvK5dTLsmG1ydCkr7hTKs/edit#heading=h.i6jm8kpl7vkq).

**Comment by alhayward** [comment]
Created #76 to continue work in developing visualizations and examples that illustrate our recommended Approach #1 (short-term) and Approach #3 (long-term) above.
