### ISSUE TITLE
Universal set of blocking keys

### ISSUE THREAD

**Issue by ericbuckley** [CDCgov/RecordLinker#26]
## Summary
As we move towards a concept of only have N number of blocking keys available to customers, we need to determine exactly what those keys should be.

## Acceptance Criteria
- [x] A recommendation of ~10 blocking keys customers can pick from

## Details / Tasks
- [x] Develop recommendation of ~10 blocking keys
- [ ] Gain DIBBs team feedback on recommendation

We have 7 keys currently in use by the DIBBS_* algorithms, so at the very least we'll need these 7 going forward.  There are likely a few more, which may provide good value for customers to optionally "block" with when retrieving from the database.

- birthdate
- sex
- zipcode
- last 4 of mrn
- first 4 of first name
- first 4 of last name
- first 4 of address

## Background / Context
Having a universal set of blocking keys, rather than unlimited, has many advantages.  a) its easier to drive a UI for users to configure their algorithm b) we can optimize the database up front for the appropriate blocking key indexes c) we can limit customers to keys we know are useful and not allow them to make too many inappropriate decisions.

**Comment by ericbuckley** [comment]
@alhayward now that we're in the process of [adding more identifiers](https://github.com/CDCgov/RecordLinker/pull/88) to the list of feature comparisons, I'm wondering if it makes sense to also block on those?  For example, I could see similar reason for wanting to block on the last 4 of SSN if blocking on the last 4 of MRN provides value.  In a PHA where SSN is more readily available than MRN, this might be a better blocking key.  Thoughts?

**Comment by alhayward** [comment]
# Recommendation (Draft)
Based on literature review of the latest patient Record Linkage algorithms and feedback from the DIBBs team, the following fixed set of 10 Blocking Keys are recommended:

**Existing**
1. DOB
2. Sex
3. ZIP
4. Last 4 of MRN
5. First 4 of First Name
6. First 4 of Last Name
7. First 4 of Address

**New**
1. SSN (recommendation based on [1])
2. Phone Number (recommendation based on [1])
3. Email (recommendation from DIBBs team)

# Rationale
**SSN**
* Similar to MRN, SSN is recommended as a Blocking Key due to its uniqueness by patient and thus potential for predictive power in record linkage. SSN was a key feature that the DIBBs team had intended to use for Matching and Blocking in their previous partnership with LAC, however SSN data was unavailable in the production data they gained access to. [1]
* As a Blocking Key, SSN will be most powerful when the data is high quality (e.g., few errors and good coverage). However, SSN may suffer from field missingness, which would impact linkage performance (in both Blocking and Matching). Additionally, HIPAA and state data privacy laws may prohibit sharing information on unique identifiers such as SSN, making it potentially difficult to utilize in patient record linkage systems. [1] 

**Phone Number**
* Similarly to SSN, Phone Number was also a key feature documented in the DIBBs team's previous work with LAC. Phone Number in particular has shown high presence/coverage as a patient identifier in eCR and ELR data. Based on recent research, Phone Number was present >95% of the time across settings and health systems. In the case of field missingness, research has shown that data "enhancement" can increase coverage of Phone Number data by 34.4% [1].

**Email**
* This Blocking Key was recommended by the DIBBs team due to its common uniqueness by patient, highlighting its potential for predictive power in patient record linkage.

# References
1. [Record Linkage Product Requirements Document (PRD) & Literature Review](https://cdc.sharepoint.com/:w:/r/teams/CSELS-DHIS-ISB-NBS/_layouts/15/Doc.aspx?sourcedoc=%7BA6169829-A703-4DB4-98FB-6FCB50BECC01%7D&file=RL-PRD-and-Lit-Review.docx&action=default&mobileredirect=true)
2. [Record Linkage Internal Report](https://docs.google.com/document/d/1Gwu8V6d2V0IlcK9KQf5kIHPcgoQudln3Y330cqfwJOc/edit?tab=t.0#heading=h.uv90c5i8c0dy)

**Comment by ericbuckley** [comment]
@alhayward I couple of thoughts / questions pertaining to these recommendations.

1. Re `SSN`. This makes a lot of sense and is aligned with some similar thinking I had with adding Driver's License as well.  Right now the MRN blocking key only uses the last 4 characters, would we do the same with `SSN` or do you recommend a change to either or both of these.  Also, as we move over to using identifier triplets, both SSN and MRN will be migrated to use that feature.  Are there any changes you'd recommend to the [existing proposal for identifier blocking keys](https://github.com/CDCgov/RecordLinker/blob/main/rfc/001-identifier-triplets.md#blocking)?

2. Re `telecom` phone numbers.  Phone numbers are likely to show up in a variety of formats (eg 123-456-7890, 123.456.7890, (123) 456-7890, 456-7890, 456-7890 ext 000).  I'm guessing we should run some sort of normalization step on these values first to make sure the comparisons work as expected.  Any recommendations to how we format are telecom phone blocking keys?  For example, should we just try to extract the "7890" portion in the examples above and use that as a blocking value?

3. Re `telecom` emails.   Emails will suffice from the same problems that names will, they can be indefinitely long.  Our blocking values are [currently limited to 20 characters or less](https://github.com/CDCgov/RecordLinker/blob/main/src/recordlinker/models/mpi.py#L14).  Do you recommend a strategy for only using the first 4 characters of an email or maybe we use the first 4 characters of the email, plus the first 4 characters after the "@" symbol?

4. Do you recommend removing any existing blocking keys? I remember in one of our conversations someone on the DIBBs team mentioned limited value from the `SEX` key because it typically just reduces the pool of values by 50%, and good keys, from a performance perspective, should really be reducing much more of the pool.

**Comment by alhayward** [comment]
@ericbuckley The most robust way to answer your questions, and ultimately identify the optimal Blocking Keys to recommend, is to implement and evaluate the performance of these Blocking Keys on (production) data. Similar to the way the DIBBs team identified the optimal Matching Features. I added a **Long-Term Approach** section to clarify/advocate for this. However, given the limitations of synthetic data and gaining access to production data at this time, here are my responses:
1. Last 4 of SSN. I updated the above Recommendation to clarify this. I think your existing proposal is a good start for now.
2. Yes, we should definitely standardize Phone Number. I think stripping any non-digit characters and asserting length is a good start. To more effectively answer your question, we should test the performance of blocking on all digits vs. last 4 with data. My hunch is that, because phone numbers may be less unique than IDs like SSN and MRN, using only the last four won't be as representative of the string value (as a "sample") to represent its uniqueness, and thus will not have as much predictive power as last 4 of SSN or MRN. Thus, utilizing all the data in Phone Number would be beneficial.  To my understand the "last 4" approach is really most effective when the underlying data is unique (e.g., IDs like SSN, MRN). 
3. Ideally, we would use the entire email string. If this causes performance issues, I'm not sure which transformation approach (e.g., first 4, first 4 and first 4 after "@") would be most effective without testing them on data. We should utilize the performance testing framework to implement and evaluate different transformations of email and choose the one that demonstrates the highest performance (in terms of match accuracy, and system performance if desired) to make the most data-driven decision.
4. No, I do not recommend removing any existing Blocking Keys right now. I would advocate for utilizing data to test and justify their removal. I also anticipate NBS and STLTs may be looking to use `SEX` as a Blocking Key, as this feature often comes up in the literature as being used for Matching and Blocking [1, 2].
